In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Collecting mlxtend
  Downloading mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: scipy>=1.16.3 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.17.0)
Requirement already satisfied: numpy>=2.3.5 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (2.4.1)
Requirement already satisfied: pandas>=2.3.3 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.8.0 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (12.1.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from pandas>=2.3.3->mlxtend) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\shash\AppData\Roaming\Python\Python314\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------------------------------ --------- 1.0/1.4 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 5.5 MB/s  0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.25.0

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [17]:
df = pd.read_csv('Retail_Data.csv')
df = df.iloc[:,1:]
df.head()
df.describe()

  Product1 Product2 Product3
0    Bread   Butter      Egg
1    Bread   Butter      Egg
2    Bread   Butter      Egg
3    Bread   Butter      Egg
4    Bread   Butter      Egg

       Product1 Product2 Product3
count      2000     2000     2000
unique        4        5        3
top       Bread      Jam      Egg
freq        702      658     1152

In [16]:
df1 = pd.get_dummies(df)
df1.head()
df1.describe()

,Product1_Bread,Product1_Fruits,Product1_Juice,Product1_Nachos,Product2_Butter,Product2_JAM,Product2_Jam,Product2_Salsa,Product2_Vegetable,Product3_Dairy,Product3_Egg,Product3_Salad
0,True,False,False,False,True,False,False,False,False,False,True,False
1,True,False,False,False,True,False,False,False,False,False,True,False
2,True,False,False,False,True,False,False,False,False,False,True,False
3,True,False,False,False,True,False,False,False,False,False,True,False
4,True,False,False,False,True,False,False,False,False,False,True,False

,Product1_Bread,Product1_Fruits,Product1_Juice,Product1_Nachos,Product2_Butter,Product2_JAM,Product2_Jam,Product2_Salsa,Product2_Vegetable,Product3_Dairy,Product3_Egg,Product3_Salad
count,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000
unique,2,2,2,2,2,2,2,2,2,2,2,2
top,False,False,False,False,False,False,False,False,False,False,True,False
freq,1298,1635,1507,1560,1507,1976,1342,1607,1568,1594,1152,1558

In [9]:
df1.shape

(2000, 12)

In [22]:
# find rules which have at least 5% support level
frequent_items = apriori(df1, min_support=0.02, use_colnames=True)
type(frequent_items)
frequent_items.shape
frequent_items

# build rules with minimum Lift of 1
rules = association_rules(frequent_items, metric="lift", min_threshold=1)
type(rules)
rules.shape
rules

pandas.core.frame.DataFrame

(42, 2)

    support                                           itemsets
0    0.3510                                   (Product1_Bread)
1    0.1825                                  (Product1_Fruits)
2    0.2465                                   (Product1_Juice)
3    0.2200                                  (Product1_Nachos)
4    0.2465                                  (Product2_Butter)
5    0.3290                                     (Product2_Jam)
6    0.1965                                   (Product2_Salsa)
7    0.2160                               (Product2_Vegetable)
8    0.2030                                   (Product3_Dairy)
9    0.5760                                     (Product3_Egg)
10   0.2210                                   (Product3_Salad)
11   0.2145                  (Product2_Butter, Product1_Bread)
12   0.1280                     (Product2_Jam, Product1_Bread)
13   0.1005                   (Product3_Dairy, Product1_Bread)
14   0.2505                     (Product3_Egg, Product1_Bread)
15   0.1705              (Product1_Fruits, Product2_Vegetable)
16   0.1825                  (Product3_Salad, Product1_Fruits)
17   0.2010                     (Product1_Juice, Product2_Jam)
18   0.0455               (Product1_Juice, Product2_Vegetable)
19   0.2080                     (Product3_Egg, Product1_Juice)
20   0.0385                   (Product3_Salad, Product1_Juice)
21   0.0320                 (Product1_Nachos, Product2_Butter)
22   0.1880                  (Product2_Salsa, Product1_Nachos)
23   0.1025                  (Product1_Nachos, Product3_Dairy)
24   0.1175                    (Product3_Egg, Product1_Nachos)
25   0.0520                  (Product2_Butter, Product3_Dairy)
26   0.1945                    (Product3_Egg, Product2_Butter)
27   0.0720                     (Product2_Jam, Product3_Dairy)
28   0.2570                       (Product3_Egg, Product2_Jam)
29   0.0790                   (Product2_Salsa, Product3_Dairy)
30   0.1175                     (Product2_Salsa, Product3_Egg)
31   0.2090               (Product3_Salad, Product2_Vegetable)
32   0.0200  (Product3_Dairy, Product1_Bread, Product2_Butter)
33   0.1945    (Product3_Egg, Product1_Bread, Product2_Butter)
34   0.0720     (Product3_Dairy, Product2_Jam, Product1_Bread)
35   0.0560       (Product3_Egg, Product2_Jam, Product1_Bread)
36   0.1705  (Product3_Salad, Product1_Fruits, Product2_Veg...
37   0.2010       (Product3_Egg, Product1_Juice, Product2_Jam)
38   0.0385  (Product3_Salad, Product1_Juice, Product2_Vege...
39   0.0320  (Product1_Nachos, Product3_Dairy, Product2_But...
40   0.0705  (Product2_Salsa, Product1_Nachos, Product3_Dairy)
41   0.1175    (Product2_Salsa, Product3_Egg, Product1_Nachos)

pandas.core.frame.DataFrame

(82, 14)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Product1_Bread),(Product2_Butter),0.3510,0.2465,0.2145,0.611111,2.479153,1.0,0.127978,1.937571,0.919316,0.560052,0.483890,0.740647
1,(Product2_Butter),(Product1_Bread),0.2465,0.3510,0.2145,0.870183,2.479153,1.0,0.127978,4.999328,0.791820,0.560052,0.799973,0.740647
2,(Product2_Jam),(Product1_Bread),0.3290,0.3510,0.1280,0.389058,1.108427,1.0,0.012521,1.062294,0.145783,0.231884,0.058641,0.376865
3,(Product1_Bread),(Product2_Jam),0.3510,0.3290,0.1280,0.364672,1.108427,1.0,0.012521,1.056148,0.150725,0.231884,0.053163,0.376865
4,(Product1_Bread),(Product3_Dairy),0.3510,0.2030,0.1005,0.286325,1.410467,1.0,0.029247,1.116754,0.448405,0.221610,0.104548,0.390699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,"(Product2_Salsa, Product1_Nachos)",(Product3_Egg),0.1880,0.5760,0.1175,0.625000,1.085069,1.0,0.009212,1.130667,0.096552,0.181748,0.115566,0.414497
78,"(Product3_Egg, Product1_Nachos)",(Product2_Salsa),0.1175,0.1965,0.1175,1.000000,5.089059,1.0,0.094411,inf,0.910482,0.597964,1.000000,0.798982
79,(Product2_Salsa),"(Product3_Egg, Product1_Nachos)",0.1965,0.1175,0.1175,0.597964,5.089059,1.0,0.094411,2.195079,1.000000,0.597964,0.544436,0.798982
80,(Product3_Egg),"(Product2_Salsa, Product1_Nachos)",0.5760,0.1880,0.1175,0.203993,1.085069,1.0,0.009212,1.020092,0.184906,0.181748,0.019696,0.414497
81,(Product1_Nachos),"(Product2_Salsa, Product3_Egg)",0.2200,0.1175,0.1175,0.534091,4.545455,1.0,0.091650,1.894146,1.000000,0.534091,0.472058,0.767045

In [21]:
# Top 10 rules with highest support
rules.sort_values('support', ascending = False).head(10)

# Top 10 rules with highest confidence
rules.sort_values('confidence', ascending = False). head(10)

# Top 10 rules with highest confidence
rules.sort_values('lift', ascending = False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
26,(Product3_Egg),(Product2_Jam),0.5760,0.3290,0.2570,0.446181,1.356172,1.0,0.067496,1.211586,0.619411,0.396605,0.174636,0.613668
27,(Product2_Jam),(Product3_Egg),0.3290,0.5760,0.2570,0.781155,1.356172,1.0,0.067496,1.937444,0.391401,0.396605,0.483856,0.613668
6,(Product3_Egg),(Product1_Bread),0.5760,0.3510,0.2505,0.434896,1.239019,1.0,0.048324,1.148461,0.454977,0.370288,0.129269,0.574286
7,(Product1_Bread),(Product3_Egg),0.3510,0.5760,0.2505,0.713675,1.239019,1.0,0.048324,1.480836,0.297242,0.370288,0.324706,0.574286
1,(Product2_Butter),(Product1_Bread),0.2465,0.3510,0.2145,0.870183,2.479153,1.0,0.127978,4.999328,0.791820,0.560052,0.799973,0.740647
0,(Product1_Bread),(Product2_Butter),0.3510,0.2465,0.2145,0.611111,2.479153,1.0,0.127978,1.937571,0.919316,0.560052,0.483890,0.740647
32,(Product3_Salad),(Product2_Vegetable),0.2210,0.2160,0.2090,0.945701,4.378247,1.0,0.161264,14.438667,0.990498,0.916667,0.930742,0.956647
33,(Product2_Vegetable),(Product3_Salad),0.2160,0.2210,0.2090,0.967593,4.378247,1.0,0.161264,24.037714,0.984181,0.916667,0.958399,0.956647
14,(Product3_Egg),(Product1_Juice),0.5760,0.2465,0.2080,0.361111,1.464954,1.0,0.066016,1.179391,0.748549,0.338487,0.152105,0.602462
15,(Product1_Juice),(Product3_Egg),0.2465,0.5760,0.2080,0.843813,1.464954,1.0,0.066016,2.714701,0.421214,0.338487,0.631635,0.602462

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
11,(Product1_Fruits),(Product3_Salad),0.1825,0.2210,0.1825,1.000000,4.524887,1.0,0.142168,inf,0.952905,0.825792,1.000000,0.912896
44,"(Product2_Jam, Product3_Dairy)",(Product1_Bread),0.0720,0.3510,0.0720,1.000000,2.849003,1.0,0.046728,inf,0.699353,0.205128,1.000000,0.602564
50,"(Product1_Fruits, Product2_Vegetable)",(Product3_Salad),0.1705,0.2210,0.1705,1.000000,4.524887,1.0,0.132820,inf,0.939120,0.771493,1.000000,0.885747
56,"(Product1_Juice, Product2_Jam)",(Product3_Egg),0.2010,0.5760,0.2010,1.000000,1.736111,1.0,0.085224,inf,0.530663,0.348958,1.000000,0.674479
65,"(Product1_Nachos, Product2_Butter)",(Product3_Dairy),0.0320,0.2030,0.0320,1.000000,4.926108,1.0,0.025504,inf,0.823347,0.157635,1.000000,0.578818
60,"(Product3_Salad, Product1_Juice)",(Product2_Vegetable),0.0385,0.2160,0.0385,1.000000,4.629630,1.0,0.030184,inf,0.815393,0.178241,1.000000,0.589120
76,"(Product2_Salsa, Product3_Egg)",(Product1_Nachos),0.1175,0.2200,0.1175,1.000000,4.545455,1.0,0.091650,inf,0.883853,0.534091,1.000000,0.767045
78,"(Product3_Egg, Product1_Nachos)",(Product2_Salsa),0.1175,0.1965,0.1175,1.000000,5.089059,1.0,0.094411,inf,0.910482,0.597964,1.000000,0.798982
37,"(Product3_Egg, Product2_Butter)",(Product1_Bread),0.1945,0.3510,0.1945,1.000000,2.849003,1.0,0.126231,inf,0.805711,0.554131,1.000000,0.777066
33,(Product2_Vegetable),(Product3_Salad),0.2160,0.2210,0.2090,0.967593,4.378247,1.0,0.161264,24.037714,0.984181,0.916667,0.958399,0.956647

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
79,(Product2_Salsa),"(Product3_Egg, Product1_Nachos)",0.1965,0.1175,0.1175,0.597964,5.089059,1.0,0.094411,2.195079,1.000000,0.597964,0.544436,0.798982
78,"(Product3_Egg, Product1_Nachos)",(Product2_Salsa),0.1175,0.1965,0.1175,1.000000,5.089059,1.0,0.094411,inf,0.910482,0.597964,1.000000,0.798982
68,(Product3_Dairy),"(Product1_Nachos, Product2_Butter)",0.2030,0.0320,0.0320,0.157635,4.926108,1.0,0.025504,1.149146,1.000000,0.157635,0.129789,0.578818
65,"(Product1_Nachos, Product2_Butter)",(Product3_Dairy),0.0320,0.2030,0.0320,1.000000,4.926108,1.0,0.025504,inf,0.823347,0.157635,1.000000,0.578818
63,(Product2_Vegetable),"(Product3_Salad, Product1_Juice)",0.2160,0.0385,0.0385,0.178241,4.629630,1.0,0.030184,1.170051,1.000000,0.178241,0.145336,0.589120
60,"(Product3_Salad, Product1_Juice)",(Product2_Vegetable),0.0385,0.2160,0.0385,1.000000,4.629630,1.0,0.030184,inf,0.815393,0.178241,1.000000,0.589120
76,"(Product2_Salsa, Product3_Egg)",(Product1_Nachos),0.1175,0.2200,0.1175,1.000000,4.545455,1.0,0.091650,inf,0.883853,0.534091,1.000000,0.767045
81,(Product1_Nachos),"(Product2_Salsa, Product3_Egg)",0.2200,0.1175,0.1175,0.534091,4.545455,1.0,0.091650,1.894146,1.000000,0.534091,0.472058,0.767045
51,(Product3_Salad),"(Product1_Fruits, Product2_Vegetable)",0.2210,0.1705,0.1705,0.771493,4.524887,1.0,0.132820,3.630089,1.000000,0.771493,0.724525,0.885747
50,"(Product1_Fruits, Product2_Vegetable)",(Product3_Salad),0.1705,0.2210,0.1705,1.000000,4.524887,1.0,0.132820,inf,0.939120,0.771493,1.000000,0.885747

## Example 2

In [3]:
# Print many statements at same time using the below command
from IPython. core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Import packages
import pandas as pd
from mlxtend. frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [4]:
# data is from http://archive.ics.uci.edu/ml/datasets/online+retail
df = pd.read_excel('Online_Retail.xlsx')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
df.shape

(541909, 8)

In [6]:
# find out # unique countries
df.Country.nunique()
df.Country.unique()

38

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [9]:
# Separate out Germany for further analysis
df1 = df[df.Country == "Japan"]
df1.shape

(358, 8)

In [10]:
# Reorganize data
bskt = pd.pivot_table(df1,index='InvoiceNo', columns='Description',values='Quantity', fill_value=0)
bskt

Description,I LOVE LONDON MINI BACKPACK,12 PENCILS TALL TUBE RED RETROSPOT,20 DOLLY PEGS RETROSPOT,3 HOOK HANGER MAGIC GARDEN,36 PENCILS TUBE RED RETROSPOT,4 TRADITIONAL SPINNING TOPS,5 HOOK HANGER MAGIC TOADSTOOL,5 HOOK HANGER RED MAGIC TOADSTOOL,60 CAKE CASES DOLLY GIRL DESIGN,ABC TREASURE BOOK BOX,...,VINTAGE DONKEY TAIL GAME,VINTAGE KEEPSAKE BOX PARIS DAYS,VINTAGE LEAF MAGNETIC NOTEPAD,WALL TIDY RETROSPOT,WHITE HEART CONFETTI IN TUBE,WHITE SOAP RACK WITH 2 BOTTLES,WHITE WIRE EGG HOLDER,WOODEN HAPPY BIRTHDAY GARLAND,WOODEN SCHOOL COLOURING SET,WORLD WAR 2 GLIDERS ASSTD DESIGNS
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
537218,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
538397,0.0,0.0,96.0,36.0,0.0,0.0,36.0,48.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,12.0,24.0,0.0,0.0
543179,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
543518,0.0,0.0,0.0,36.0,0.0,0.0,0.0,96.0,0.0,0.0,...,0.0,24.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0
545448,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
545645,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
545845,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
548993,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,...,0.0,0.0,0.0,0.0,0.0,18.0,0.0,0.0,72.0,0.0
550344,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,288.0,576.0
553045,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
557670,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
561063,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
561388,0.0,48.0,0.0,0.0,48.0,0.0,0.0,0.0,0.0,0.0,...,36.0,0.0,48.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
566623,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
572763,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
572869,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
576923,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,48.0,0.0,0.0,0.0,0.0,0.0
579498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C540392,0.0,0.0,-3.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C545446,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C545739,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C545891,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C545892,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C548731,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C551015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C564138,0.0,0.0,0.0,0.0,-16.0,0.0,0.0,0.0,0.0,0.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C580832,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
bskt.shape

(28, 217)

In [12]:
# Write a function to do 0 or 1 coding for all items

def cod(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

bskt_sets = bskt.apply(lambda col: col.map(cod))

In [ ]:
#applying apriori algorithm to generate rules which have support more than 0.05
frequent_itemsets = apriori(bskt_sets.astype(bool), min_support=0.05, use_colnames=True)
frequent_itemsets.head()

In [ ]:
# find rules with Lift more than one
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(RED RETROSPOT CHARLOTTE BAG),(ABC TREASURE BOOK BOX ),0.054545,0.072727,0.054545,1.000000,13.750000,1.0,0.050579,inf,0.980769,0.75,1.000000,0.875000
1,(ABC TREASURE BOOK BOX ),(RED RETROSPOT CHARLOTTE BAG),0.072727,0.054545,0.054545,0.750000,13.750000,1.0,0.050579,3.781818,1.000000,0.75,0.735577,0.875000
2,(ABC TREASURE BOOK BOX ),(WOODLAND CHARLOTTE BAG),0.072727,0.054545,0.054545,0.750000,13.750000,1.0,0.050579,3.781818,1.000000,0.75,0.735577,0.875000
3,(WOODLAND CHARLOTTE BAG),(ABC TREASURE BOOK BOX ),0.054545,0.072727,0.054545,1.000000,13.750000,1.0,0.050579,inf,0.980769,0.75,1.000000,0.875000
4,(BREAD BIN DINER STYLE IVORY),(DOORMAT UNION FLAG),0.109091,0.109091,0.072727,0.666667,6.111111,1.0,0.060826,2.672727,0.938776,0.50,0.625850,0.666667

# Articles to cover
- 45
- 46
- 57